version: "3"
services:
  mysql:
    image: mysql:8.0.29
    container_name: reversi-mysql
    platform: linux/x86_64
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reversi
      MYSQL_USER: reversi
      MUSQL_PASSWORD: password
